<a href="https://colab.research.google.com/github/otoperalias/Coyuntura/blob/main/Clases/Tema2_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ## TEMA 2. ANÁLISIS ECONÓMICO CON PYTHON

**Coyuntura y Predicción**

Universidad Pablo de Olavide, Curso 2021-22

Daniel Oto-Peralías

## Índice:

1.   Introducción
2.   Sintaxis y estructuras básicas de datos.
3.   Numpy.
4.   Pandas.
5.   Una Aplicación - Usando la PWT.

## 1. Introducción

* Python es un lenguaje de programación muy flexible e intuitivo.
* Es el lenguaje por excelencia de DATA SCIENCE.
* Contiene muchas herramientas para realizar muchos tipos de análisis y ejercicios imposibles con Excel o STATA. Permite, por ejemplo, recopilar información de internet mecánicamente.
* Es seguramente el lenguaje de programación con más perspectivas de futuro.
* Gracias a su popularidad, hay muchos recursos y ayuda on-line, empezando por la web oficial https://docs.python.org/3/contents.html

<strong> Descarga e instalación </strong>

* Lo puedes descargar directamente de la web oficial https://www.python.org/downloads/

 Incluye un editor (IDLE), el cual se puede mejorar instalando con IdLex http://idlex.sourceforge.net/

* Lo más recomendable es descargarlo a través de ANACONDA, un paquete que incluye Python, el editor Spyder, Jupyter y cientos de módulos:
https://www.anaconda.com/distribution/#download-section

* También es posible usar Python online a través de Google colab (https://colab.research.google.com), para lo cual se necesita crear una cuenta gratuita en Google.

## 2. Sintaxis y estructuras básicas de datos

* Las sangrías importan en Python (mientras en Stata se usan llaves { … } en Python sangrías).
* Las letras mayúsculas también importan.
* Cualquier texto detrás de “#” se trata como un comentario.
* Lo que aparezca entre tres comillas ```'''``` o ```"""``` se trata también como comentarios. Es muy útil cuando se trata de comentarios largos. Las comillas de cierre deben ser las mismas (!).


#### **Variables**

Las variables son objetos a los que se asignan números o texto (string).

In [ ]:
myNumber = 10
print (myNumber)

myString = "Hello , World !"
print (myString)

10
Hello , World !


---
*Tarea 1* - Asigne dos variables para que sean números (el 5 y el 25) y use el símbolo + para producir la suma de esos números. Ahora intenta restar, multiplicar y dividir.

---

In [ ]:
# Resolver Tarea 1 aquí:


---
*Tarea 2* - Asigne “Hello” a una variable y “World!" a otra. Concatene (combine) las dos variables (string variables) con el signo más, tal como agregaría números. Pista: Agregue un poco de espacio en blanco: var1 + “ “ + var2..

---

In [ ]:
# Resolver Tarea 2 aquí:


---
*Tarea 3* - Pruebe ahora a multiplicar un elemento no numérico (string): “-x-”*50

---

In [ ]:
# Resolver Tarea 2 aquí:


#### **Listas**

* Las listas son otro tipo de objeto básico en Python. Para definir una lista, separe sus elementos por comas y cierre con corchetes. 
* Algunas formas de agregar elementos a una lista:

In [ ]:
myList = [1,2,3] 
myList.append(4)
myList=myList+[5]
myList+=[6] 
myList

[1, 2, 3, 4, 5, 6]

---
*Tarea 4* - Defina una lista en la que los elementos son los dígitos de su cumpleaños.

---

In [ ]:
# Resolver Tarea 4 aquí:


* La indexación en una lista = posición de un elemento en la lista. Python comienza a contar en 0.

In [ ]:
myList
myList [0] # primer elemento en myList
len(myList) # longitud de myList
# myList [6] # da error porque no existe el element 7º
myList[5] # esto sí ;)

6

---
*Tarea 5* - De la lista definida en la Tarea 4, calcule su longitud y extraiga el último elemento.

---

In [ ]:
# Resolver tarea 5 aquí:


--- 
*Tarea 6* - Las listas pueden almacenar cualquier estructura de datos en sus elementos. Haga una lista en la que el primer elemento es el nombre del mes de su cumpleaños (string), el segundo elemento es el día del mes de su cumpleaños (un número) y el último elemento es el año de su nacimiento (también un número).

---

In [ ]:
# Resolver tarea 6 aquí:


* Además, las listas pueden contener listas.

In [ ]:
lista1=[0,1,2,3]
lista2=[lista1,"Uno","Dos"]
print(lista2)

[[0, 1, 2, 3], 'Uno', 'Dos']


* Las listas se pueden modificar borrando y añadiendo elementos:

In [ ]:
myList=["a","b","c"]
myList[0]="z" # Cambiamos el primer elemento
print(myList)

['z', 'b', 'c']


* Cuando una lista se asigna a otra, cambios en la primera lista afectan a la nueva:

In [ ]:
myList=["a","b","c","d","e"]
newList=myList
print(newList)
myList+=["Z"]
print(newList)

['a', 'b', 'c', 'd', 'e']
['a', 'b', 'c', 'd', 'e', 'Z']


* Para evitarlo, usamos la función copiar:

In [ ]:
myList=["a","b","c","d","e"]
newList=myList.copy()
print(newList)
myList+=["Z"]
print(newList)

['a', 'b', 'c', 'd', 'e']
['a', 'b', 'c', 'd', 'e']


#### **Funciones**

* Las funciones son equivalentes a los programas (.ado) en Stata. 
* Son muy útiles si vamos a hacer algo de manera reiterada.
* La definición de una función comienza con ```def ```, luego el nombre de la función seguido de paréntesis. Cualquier parámetro o argumento que tome la función debe aparecer entre paréntesis. Un doble punto sigue a los paréntesis, y el resto de la función tiene un nivel adicional de sangría.

In [ ]:
def printWord(word): # define la funciión “printWord” que toma un parámetro “word”
	print("La palabra que has escrito es "+ word)
 
printWord("Python") # así se ejecuta la función

La palabra que has escrito es Python


* Las funciones no contienen necesariamente argumentos, como por ejemplo esta:

In [ ]:
def hello_world():
  print("Hello world!")
hello_world()

Hello world!


* Es buena práctica documentar lo que hace la función (útil para nosotros en el futuro y para terceros que usen nuestro código):

In [ ]:
def hello_world():
  '''Esta función escribe ¡Hola mundo! en inglés y no tiene argumentos'''
  print("Hello world")

* La palabra ```return``` tiene un significado especial ya que permite guardar/asignar el output de la función. 

In [ ]:
def addNums(num1,num2):
  '''Esta función suma dos números'''
  return num1+num2
result=addNums(1,10)
print(result)

11


---
*Tarea 7* - Defina una función “multNums” cuyo output sea el producto de dos números. Pruébelo asignando result=multNums (2,3) y luego imprima el resultado. 
¿Y cuánto sería multNums (2, resultado)? (o sea, el resultado anterior va ahora dentro de la función).

---
(clicar en ```+ Código``` arriba para crear una celda de código y resolver la tarea)

#### **Condiciones (if/else) y bucles**

* Las condiciones ```if/else``` se usan para ejecutar un código si se cumple la condición especificada:

In [ ]:
n=8
if n==1:
  num="uno"
elif n==2:
  num="dos"
elif n==3:
  num="tres"
else:
  num="Mayor que tres"
print(num)

Mayor que tres


* El bucle ```for``` itera sobre un objeto compuesto de varios elementos (susceptible de iteración, como una lista), de manera que ejecutará un comando tantas veces como elementos tenga el objeto sobre el que se intera:

In [ ]:
lista=[1,2,3,4,5,6,7,8]
for x in lista:
  print(x)

1
2
3
4
5
6
7
8


* Con el bucle ```for``` también se puede interar sobre un rango numérico que definamos sobre la marcha:

In [ ]:
for x in range(1,9):
  print(x)

1
2
3
4
5
6
7
8


* *Observa que el número 9 no se incluye en el rango. Esto es así en general: el último número no se incluye.*

* Otro bucle importante es el bucle ```while```, que no vamos a usar en este curso pero podéis aprender sobre él aquí: https://realpython.com/python-while-loop/



---
*Tarea 8* - Use un bucle ```for``` para imprimir cada elemento de la lista ["manzanas", "plátanos", "naranjas"].

---

---
*Tarea 9* - Use un bucle ```for``` para imprimir cada número del 50 al 100, ambos extremos inclusive.

---

---
*Tarea 10* - Defina la función “evaluacion(nombre)” que tome un string y devuelva “OK" si el nombre introducido es "Python" o "Stata“, y que devuelta “MAL” en caso contrario. Pruebe que la función está correctamente programada usando la siguiente lista de palabras: "Python", "SPSS", "Stata", "Java", "MATLAB", "Eviews" (Pista1: use los condicionales if y else. Pista 2: puede usar un loop para simplificar la tarea).

---

#### **Booleans: True/False**

* Con frecuencia es necesario evaluar (comprobar) si algo es verdadero o no. Por ejemplo, cuando usamos ```if```.

* Python usa operadores de comparación intuitivos, muchos de ellos os deben resultar familiares:
    

1.   ```<```	strictly less than
2.   ```<=```	less than or equal
3.   ```>``` strictly greater than
4.   ```>=```	greater than or equal
5.   ```==```	equal
6.   ```!=```	not equal
7.   ```is```	object identity
8.   ```is not```	negated object identity

```python
1>3 # da False
3>1 # da True
1 in [1,2,3] # da True
"sevilla" in ["sevilla", "cadiz", "malaga“] # da True
```
    
    



#### **Tuples**

* Como una lista, un tuple es un conjunto ordenado de valores. A diferencia de una lista, los tuples son inmutables (no se pueden cambiar una vez que se definen). 
* También es importante saber acerca de tuples porque algunos métodos devuelven tuples, no listas. 
* Mientras que las listas se definen entre corchetes, los tuples se declaran entre paréntesis.

In [2]:
row1=("nombre","apellido")
row2=("Manuel","Martínez")
row3=("Juan" , "Pérez")
print(row2[0])

Manuel


In [4]:
row2.append("Gutiérrez") # da error porque son inmutables

#### **Diccionarios**

* Los dictionaries relacionan claves con valores (key=>value): sabiendo una clave, se conoce rápidamente su valor, como en un diccionario real.
* Para definir un diccionario: ```{ key1: value1 , key2: value2 , key3: value3 , key4: value4 , ...}```

In [9]:
myDict = {"Manuel Martínez":"Notable","Juan Pérez": "Aprobado"}
print(myDict["Manuel Martínez"])

Notable


In [6]:
notas={"Juan García":9,"Alonso Ramos":8.5,"Federico Gutiérrez":5}
print(notas["Juan García"])

9


In [8]:
notas2={12253697:9,89966369:8.5,87777898:5}
print(notas2[87777898])

5


In [ ]:
print(notas2[87777777]) # da error porque la clave no existe

* Se pueden obtener fácilmente todas las claves del diccionario en una lista y hacer un bucle con ellas:

In [12]:
calificaciones={"Juan":9,"Alonso":8.5,"Manuel":5,"María":9,"Cármen":8,"Daniel":10}
print(calificaciones.keys())
for k in calificaciones.keys():
  print("La calificación de "+k+" es un "+str(calificaciones[k])+".")

dict_keys(['Juan', 'Alonso', 'Manuel', 'María', 'Cármen', 'Daniel'])
La calificación de Juan es un 9.
La calificación de Alonso es un 8.5.
La calificación de Manuel es un 5.
La calificación de María es un 9.
La calificación de Cármen es un 8.
La calificación de Daniel es un 10.


---
*Tarea 11* - Defina mydict = {1: "A", 2: "B", 3: "C"}. ¿Qué valor es mydict [1]? Use un bucle for para imprimir cada clave por separado. Ahora imprima cada valor por separado. ¿Puede poner una condición if dentro de un ciclo for que imprima las claves si sus valores son "C"?

---

## 3. Numpy

* Numpy es un módulo fundamental para cálculo numérico y para operar con vectores (one-dimensional arrays) y matrices (Multi-dimensional arrays), siendo la base sobre la que operan otros módulos.
* Los módulos (o librerías) son conjuntos de funciones que se deben instalar e importar antes de poder usarse (instalando Python a través de Anaconda nos facilita esta labor porque contiene cientos de módulos ya instalados; lo mismo si usamos Google Colab):

```
import numpy as np
```



* Hay muchas maneras de crear vectores y matrices. Algunos ejemplos:

In [13]:
import numpy as np
an_array = np.array([3, 33, 333])
print(an_array)
print(an_array.shape) # preguntamos cuál es la dimensión
print(an_array[0], an_array[1], an_array[2])  # imprimir de manera independiente cada elemento
an_array[0] =888 # modificamos el vector
print(an_array)

[  3  33 333]
(3,)
3 33 333
[888  33 333]


* Matrices (ndarrray rank >=2):

In [14]:
another = np.array([[11,12,13],[21,22,23]])   # rank 2 array
print(another)  
print("Las dimensiones son 2 filas, 3 columnas: ", another.shape)
print("Obteniendo elementos [0,0], [0,1], y [1,0] del ndarray o matriz: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

[[11 12 13]
 [21 22 23]]
Las dimensiones son 2 filas, 3 columnas:  (2, 3)
Obteniendo elementos [0,0], [0,1], y [1,0] del ndarray o matriz:  11 ,  12 ,  21


* Matrices con elementos aleatorios (entre otras posibilidades):

In [15]:
aleatorio = np.random.random((4,4))
print(aleatorio)

[[0.39147214 0.73805993 0.30817163 0.10008048]
 [0.12123315 0.84573125 0.17699638 0.17668416]
 [0.3020193  0.05345113 0.41915774 0.21491345]
 [0.88820343 0.93389394 0.49222073 0.11363672]]


* Al igual que las listas, se puede extraer información sobre elementos o partes concretas de los ndarrays, y modificarse elementos concretos:

In [17]:
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [18]:
col0=an_array[:,0] #todas las filas de la primera columna
print(col0)

[11 21 31]


In [19]:
col0[1]=9999
print(col0)
print(an_array) # observa que se modifica la matriz original

[  11 9999   31]
[[  11   12   13   14]
 [9999   22   23   24]
 [  31   32   33   34]]


* Una herramienta interesante es el uso de filtros:

In [21]:
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)
print(an_array[an_array>15])

[[11 12]
 [21 22]
 [31 32]]
[21 22 31 32]


In [24]:
an_array[(an_array>15) & (an_array<30)]

array([21, 22])

*Observa que aquí no usamos la funcion print(), pero se muestra el output. Esta manera de mostrar el output es válida solo si ejecutamos una línea de código o solo estamos interesados en que nos muestre la última línea ejecutada:*

In [25]:
an_array[(an_array>1)]
an_array[(an_array>10)]
an_array[(an_array>20 )]

array([21, 22, 31, 32])

* Operaciones aritméticas:

In [26]:
#Operaciones aritméticas
x = np.array([[111,112],[121,122]])
y = np.array([[211.1,212.1],[221.1,222.1]])
# Suma
print(x + y)  # Es equivalente:print(np.add(x, y))
# Resta
print(x - y) # Es equivalente: print(np.subtract(x, y))
# Multiplicación
print(x * y) # Es equivalente: print(np.multiply(x, y)) => ≠ a multiplic. matricial!
# División
print(x / y)  # Es equivalente: print(np.divide(x, y))
# Raiz cuadrada
print(np.sqrt(x))
# Elevar al cuadrado
print(x**2)

[[322.1 324.1]
 [342.1 344.1]]
[[-100.1 -100.1]
 [-100.1 -100.1]]
[[23432.1 23755.2]
 [26753.1 27096.2]]
[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]
[[10.53565375 10.58300524]
 [11.         11.04536102]]
[[12321 12544]
 [14641 14884]]


*Observar que, en Python, elevar a alguna potencia es doble asterisco* ```**``` (!)

* Operaciones estadísticas y otras:

In [27]:
arr = 10 * np.random.randn(2,5)  # Crear una matriz aleatoria 2x5 a partir de N(0,1)
print(arr)
media=arr.mean()
print(media) # Se puede imprimir directamente por supuesto print(arr.mean())
print(arr.mean(axis = 1)) # calcula la media por fila (axis = 0 => por columna)
print(arr.sum()) # suma todos los elementos
arr.sort()
print(arr)

[[-13.89439525   2.939074     9.10960433 -19.23919503  -3.24689063]
 [ 11.1672459  -15.92922359  -7.28339681  -2.00430515  12.05174845]]
-2.632973379398643
[-4.86636052 -0.39958624]
-26.32973379398643
[[-19.23919503 -13.89439525  -3.24689063   2.939074     9.10960433]
 [-15.92922359  -7.28339681  -2.00430515  11.1672459   12.05174845]]


## 3. Pandas

* **pandas** es una librería de Python para el análisis de datos. 
* Ofrece una serie de operaciones de exploración, limpieza y transformación de datos que son fundamentales para trabajar con datos en Python.
* **pandas** se basa en **numpy** y **scipy** y proporciona estructuras de datos fáciles de usar y funciones de manipulación de datos con indexación integrada.
* Las principales estructuras de datos que proporcionan los pandas son Series y DataFrames.
* Documentación de pandas: 
> https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html (*Muy recomendable que lo leais*)
> http://pandas.pydata.org/pandas-docs/stable/

```
import pandas as pd
```

* **Pandas series**

In [35]:
import pandas as pd
paro = pd.Series([20, 10, 15, 20, 8], ['Sevilla', 'Málaga', 'Jaén', 'Huelva', 'Cádiz'])
paro

Sevilla    20
Málaga     10
Jaén       15
Huelva     20
Cádiz       8
dtype: int64

In [36]:
paro.index

Index(['Sevilla', 'Málaga', 'Jaén', 'Huelva', 'Cádiz'], dtype='object')

In [37]:
paro.loc[['Sevilla','Jaén']]  # loc[]  = Filtro basado en las etiquetas del index (label based)

Sevilla    20
Jaén       15
dtype: int64

In [42]:
paro[['Sevilla','Jaén']] # Filtro equivalente a lo anterior, pero es mejor práctica usar loc[]

Sevilla    20
Jaén       15
dtype: int64

In [43]:
ser.iloc[2]  #iloc[] = Filtro por la posición en el index (la posición empieza por cero !)

15

In [39]:
paro[[4, 3, 1]] #  Filtro equivalente a lo anterior, pero es mejor práctica usar iloc[]

Cádiz      8
Huelva    20
Málaga    10
dtype: int64